environment:
  nodejs_version: "7"
cache:
 - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
build_script:
  - yarn build
test_script:
  - yarn test
build: off